services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpassword
    volumes:
      - minio_data:/data
      - ./scripts:/scripts
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-setup:
    image: minio/mc:latest
    container_name: minio-setup
    depends_on:
      - minio
    volumes:
      - ./scripts:/scripts
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /scripts/setup-minio.sh;
      "

volumes:
  minio_data: